# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "toastr-rails-sass"
  s.version = "2.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.6") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tyler Gannon", "Aaron Ciaghi"]
  s.date = "2015-03-25"
  s.description = "Toastr: Simple javascript toast notifications, plugged into the rails asset pipeline."
  s.email = ["tgannon@gmail.com", "aaron.ciaghi@gmail.com"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "lib/toastr-rails-sass.rb",
    "vendor/assets/javascripts/toastr.min.js",
    "vendor/assets/stylesheets/toastr.min.css",
    "vendor/assets/stylesheets/toastr.min.css.scss"
  ]
  s.homepage = "https://github.com/ict4g/toastr-rails-sass"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Toastr: Simple javascript toast notifications"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<toastr-rails-sass>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
      s.add_runtime_dependency(%q<railties>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<sass-rails>, [">= 3.2"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<version>, [">= 0"])
    else
      s.add_dependency(%q<toastr-rails-sass>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
      s.add_dependency(%q<railties>, [">= 3.1.0"])
      s.add_dependency(%q<sass-rails>, [">= 3.2"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<version>, [">= 0"])
    end
  else
    s.add_dependency(%q<toastr-rails-sass>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
    s.add_dependency(%q<railties>, [">= 3.1.0"])
    s.add_dependency(%q<sass-rails>, [">= 3.2"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<version>, [">= 0"])
  end
end

